apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "forgejo.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      nodePort: {{ .Values.service.httpNodePort }}
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshPort }}
      nodePort: {{ .Values.service.sshNodePort }}
